services:
  - type: web
    name: toeic-platform-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
      - key: PORT
        value: 5001

  - type: web
    name: toeic-platform-client
    env: node
    rootDir: client
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --port 5173
    envVars:
      - key: VITE_API_BASE_URL
        value: https://toeic-platform-server.onrender.com
