services:
  - type: web
    name: englishwebapp
    env: node
    plan: free
    buildCommand: |
      cd server && npm install
      cd ../client && npm install && npm run build
    startCommand: |
      cd server && npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
      - key: PORT
        value: 5001
    autoDeploy: true
